### ISSUE TITLE
When setting the bed, the bed is destroyed but players are still able to respawn

### ISSUE THREAD

**Issue by MajliTech** [Zuyte/Bedwars1058-AdminAddon#2]

**Comment by Zuyte** [comment]
Tested on 1.8.8 PaperMC & 1.18.2 PaperMC 24-03-2023 latest versions, haven't found this bug yet

**Comment by MajliTech** [comment]
Werid, i will check again today

**Comment by Zuyte** [comment]
try using this jar, ive improved the overall structure and tested it on 1.18.2
https://www.mediafire.com/file/w1msejmjo5nkzff/Bedwars1058-AdminAddon-1.1.7.jar/file

**Comment by MajliTech** [comment]
Didn't test properly, now works.
